# Autogenerated from a Treetop grammar. Edits may be lost.


#!/usr/bin/env tt
# Author::    Iñaki Baz Castillo <ibc@aliax.net>
# Copyright:: 2008 Iñaki Baz Castillo
# License::   Public Domain
# 
# ABNF syntax for IPv4 and IPv6 is defined in Appendix A of RFC 3986:
#   http://tools.ietf.org/html/rfc3986#appendix-A


module IP
  include Treetop::Runtime

  def root
    @root ||= :IPv4address
  end

  module IPv4address0
    def DIGIT1
      elements[0]
    end

    def DIGIT2
      elements[4]
    end

    def DIGIT3
      elements[8]
    end

    def DIGIT4
      elements[12]
    end

  end

  def _nt_IPv4address
    start_index = index
    if node_cache[:IPv4address].has_key?(index)
      cached = node_cache[:IPv4address][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    r1 = _nt_DIGIT
    s0 << r1
    if r1
      r3 = _nt_DIGIT
      if r3
        r2 = r3
      else
        r2 = instantiate_node(SyntaxNode,input, index...index)
      end
      s0 << r2
      if r2
        r5 = _nt_DIGIT
        if r5
          r4 = r5
        else
          r4 = instantiate_node(SyntaxNode,input, index...index)
        end
        s0 << r4
        if r4
          if has_terminal?('.', false, index)
            r6 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure('.')
            r6 = nil
          end
          s0 << r6
          if r6
            r7 = _nt_DIGIT
            s0 << r7
            if r7
              r9 = _nt_DIGIT
              if r9
                r8 = r9
              else
                r8 = instantiate_node(SyntaxNode,input, index...index)
              end
              s0 << r8
              if r8
                r11 = _nt_DIGIT
                if r11
                  r10 = r11
                else
                  r10 = instantiate_node(SyntaxNode,input, index...index)
                end
                s0 << r10
                if r10
                  if has_terminal?('.', false, index)
                    r12 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure('.')
                    r12 = nil
                  end
                  s0 << r12
                  if r12
                    r13 = _nt_DIGIT
                    s0 << r13
                    if r13
                      r15 = _nt_DIGIT
                      if r15
                        r14 = r15
                      else
                        r14 = instantiate_node(SyntaxNode,input, index...index)
                      end
                      s0 << r14
                      if r14
                        r17 = _nt_DIGIT
                        if r17
                          r16 = r17
                        else
                          r16 = instantiate_node(SyntaxNode,input, index...index)
                        end
                        s0 << r16
                        if r16
                          if has_terminal?('.', false, index)
                            r18 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure('.')
                            r18 = nil
                          end
                          s0 << r18
                          if r18
                            r19 = _nt_DIGIT
                            s0 << r19
                            if r19
                              r21 = _nt_DIGIT
                              if r21
                                r20 = r21
                              else
                                r20 = instantiate_node(SyntaxNode,input, index...index)
                              end
                              s0 << r20
                              if r20
                                r23 = _nt_DIGIT
                                if r23
                                  r22 = r23
                                else
                                  r22 = instantiate_node(SyntaxNode,input, index...index)
                                end
                                s0 << r22
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    if s0.last
      r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
      r0.extend(IPv4address0)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:IPv4address][start_index] = r0

    r0
  end

  module IPv6address0
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

    def h166
      elements[10]
    end

    def ls32
      elements[12]
    end
  end

  module IPv6address1
    def h161
      elements[1]
    end

    def h162
      elements[3]
    end

    def h163
      elements[5]
    end

    def h164
      elements[7]
    end

    def h165
      elements[9]
    end

    def ls32
      elements[11]
    end
  end

  module IPv6address2
    def h161
      elements[2]
    end

    def h162
      elements[4]
    end

    def h163
      elements[6]
    end

    def h164
      elements[8]
    end

    def ls32
      elements[10]
    end
  end

  module IPv6address3
    def h16
      elements[0]
    end

  end

  module IPv6address4
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

  end

  module IPv6address5
    def h161
      elements[1]
    end

    def h162
      elements[3]
    end

    def h163
      elements[5]
    end

    def ls32
      elements[7]
    end
  end

  module IPv6address6
    def h16
      elements[0]
    end

  end

  module IPv6address7
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

  end

  module IPv6address8
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

  end

  module IPv6address9
    def h161
      elements[1]
    end

    def h162
      elements[3]
    end

    def ls32
      elements[5]
    end
  end

  module IPv6address10
    def h16
      elements[0]
    end

  end

  module IPv6address11
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

  end

  module IPv6address12
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

  end

  module IPv6address13
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

  end

  module IPv6address14
    def h16
      elements[1]
    end

    def ls32
      elements[3]
    end
  end

  module IPv6address15
    def h16
      elements[0]
    end

  end

  module IPv6address16
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

  end

  module IPv6address17
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

  end

  module IPv6address18
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

  end

  module IPv6address19
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

  end

  module IPv6address20
    def ls32
      elements[1]
    end
  end

  module IPv6address21
    def h16
      elements[0]
    end

  end

  module IPv6address22
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

  end

  module IPv6address23
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

  end

  module IPv6address24
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

  end

  module IPv6address25
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

  end

  module IPv6address26
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

    def h166
      elements[10]
    end

  end

  module IPv6address27
    def h16
      elements[1]
    end
  end

  module IPv6address28
    def h16
      elements[0]
    end

  end

  module IPv6address29
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

  end

  module IPv6address30
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

  end

  module IPv6address31
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

  end

  module IPv6address32
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

  end

  module IPv6address33
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

    def h166
      elements[10]
    end

  end

  module IPv6address34
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end

    def h163
      elements[4]
    end

    def h164
      elements[6]
    end

    def h165
      elements[8]
    end

    def h166
      elements[10]
    end

    def h167
      elements[12]
    end

  end

  def _nt_IPv6address
    start_index = index
    if node_cache[:IPv6address].has_key?(index)
      cached = node_cache[:IPv6address][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0 = index
    i1, s1 = index, []
    r2 = _nt_h16
    s1 << r2
    if r2
      if has_terminal?(':', false, index)
        r3 = instantiate_node(SyntaxNode,input, index...(index + 1))
        @index += 1
      else
        terminal_parse_failure(':')
        r3 = nil
      end
      s1 << r3
      if r3
        r4 = _nt_h16
        s1 << r4
        if r4
          if has_terminal?(':', false, index)
            r5 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure(':')
            r5 = nil
          end
          s1 << r5
          if r5
            r6 = _nt_h16
            s1 << r6
            if r6
              if has_terminal?(':', false, index)
                r7 = instantiate_node(SyntaxNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure(':')
                r7 = nil
              end
              s1 << r7
              if r7
                r8 = _nt_h16
                s1 << r8
                if r8
                  if has_terminal?(':', false, index)
                    r9 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure(':')
                    r9 = nil
                  end
                  s1 << r9
                  if r9
                    r10 = _nt_h16
                    s1 << r10
                    if r10
                      if has_terminal?(':', false, index)
                        r11 = instantiate_node(SyntaxNode,input, index...(index + 1))
                        @index += 1
                      else
                        terminal_parse_failure(':')
                        r11 = nil
                      end
                      s1 << r11
                      if r11
                        r12 = _nt_h16
                        s1 << r12
                        if r12
                          if has_terminal?(':', false, index)
                            r13 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r13 = nil
                          end
                          s1 << r13
                          if r13
                            r14 = _nt_ls32
                            s1 << r14
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    if s1.last
      r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
      r1.extend(IPv6address0)
    else
      @index = i1
      r1 = nil
    end
    if r1
      r0 = r1
    else
      i15, s15 = index, []
      if has_terminal?('::', false, index)
        r16 = instantiate_node(SyntaxNode,input, index...(index + 2))
        @index += 2
      else
        terminal_parse_failure('::')
        r16 = nil
      end
      s15 << r16
      if r16
        r17 = _nt_h16
        s15 << r17
        if r17
          if has_terminal?(':', false, index)
            r18 = instantiate_node(SyntaxNode,input, index...(index + 1))
            @index += 1
          else
            terminal_parse_failure(':')
            r18 = nil
          end
          s15 << r18
          if r18
            r19 = _nt_h16
            s15 << r19
            if r19
              if has_terminal?(':', false, index)
                r20 = instantiate_node(SyntaxNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure(':')
                r20 = nil
              end
              s15 << r20
              if r20
                r21 = _nt_h16
                s15 << r21
                if r21
                  if has_terminal?(':', false, index)
                    r22 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure(':')
                    r22 = nil
                  end
                  s15 << r22
                  if r22
                    r23 = _nt_h16
                    s15 << r23
                    if r23
                      if has_terminal?(':', false, index)
                        r24 = instantiate_node(SyntaxNode,input, index...(index + 1))
                        @index += 1
                      else
                        terminal_parse_failure(':')
                        r24 = nil
                      end
                      s15 << r24
                      if r24
                        r25 = _nt_h16
                        s15 << r25
                        if r25
                          if has_terminal?(':', false, index)
                            r26 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r26 = nil
                          end
                          s15 << r26
                          if r26
                            r27 = _nt_ls32
                            s15 << r27
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
      if s15.last
        r15 = instantiate_node(SyntaxNode,input, i15...index, s15)
        r15.extend(IPv6address1)
      else
        @index = i15
        r15 = nil
      end
      if r15
        r0 = r15
      else
        i28, s28 = index, []
        r30 = _nt_h16
        if r30
          r29 = r30
        else
          r29 = instantiate_node(SyntaxNode,input, index...index)
        end
        s28 << r29
        if r29
          if has_terminal?('::', false, index)
            r31 = instantiate_node(SyntaxNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure('::')
            r31 = nil
          end
          s28 << r31
          if r31
            r32 = _nt_h16
            s28 << r32
            if r32
              if has_terminal?(':', false, index)
                r33 = instantiate_node(SyntaxNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure(':')
                r33 = nil
              end
              s28 << r33
              if r33
                r34 = _nt_h16
                s28 << r34
                if r34
                  if has_terminal?(':', false, index)
                    r35 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure(':')
                    r35 = nil
                  end
                  s28 << r35
                  if r35
                    r36 = _nt_h16
                    s28 << r36
                    if r36
                      if has_terminal?(':', false, index)
                        r37 = instantiate_node(SyntaxNode,input, index...(index + 1))
                        @index += 1
                      else
                        terminal_parse_failure(':')
                        r37 = nil
                      end
                      s28 << r37
                      if r37
                        r38 = _nt_h16
                        s28 << r38
                        if r38
                          if has_terminal?(':', false, index)
                            r39 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r39 = nil
                          end
                          s28 << r39
                          if r39
                            r40 = _nt_ls32
                            s28 << r40
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
        if s28.last
          r28 = instantiate_node(SyntaxNode,input, i28...index, s28)
          r28.extend(IPv6address2)
        else
          @index = i28
          r28 = nil
        end
        if r28
          r0 = r28
        else
          i41, s41 = index, []
          i42 = index
          if has_terminal?('::', false, index)
            r43 = instantiate_node(SyntaxNode,input, index...(index + 2))
            @index += 2
          else
            terminal_parse_failure('::')
            r43 = nil
          end
          if r43
            r42 = r43
          else
            i44, s44 = index, []
            r45 = _nt_h16
            s44 << r45
            if r45
              if has_terminal?('::', false, index)
                r46 = instantiate_node(SyntaxNode,input, index...(index + 2))
                @index += 2
              else
                terminal_parse_failure('::')
                r46 = nil
              end
              s44 << r46
            end
            if s44.last
              r44 = instantiate_node(SyntaxNode,input, i44...index, s44)
              r44.extend(IPv6address3)
            else
              @index = i44
              r44 = nil
            end
            if r44
              r42 = r44
            else
              i47, s47 = index, []
              r48 = _nt_h16
              s47 << r48
              if r48
                if has_terminal?(':', false, index)
                  r49 = instantiate_node(SyntaxNode,input, index...(index + 1))
                  @index += 1
                else
                  terminal_parse_failure(':')
                  r49 = nil
                end
                s47 << r49
                if r49
                  r50 = _nt_h16
                  s47 << r50
                  if r50
                    if has_terminal?('::', false, index)
                      r51 = instantiate_node(SyntaxNode,input, index...(index + 2))
                      @index += 2
                    else
                      terminal_parse_failure('::')
                      r51 = nil
                    end
                    s47 << r51
                  end
                end
              end
              if s47.last
                r47 = instantiate_node(SyntaxNode,input, i47...index, s47)
                r47.extend(IPv6address4)
              else
                @index = i47
                r47 = nil
              end
              if r47
                r42 = r47
              else
                @index = i42
                r42 = nil
              end
            end
          end
          s41 << r42
          if r42
            r52 = _nt_h16
            s41 << r52
            if r52
              if has_terminal?(':', false, index)
                r53 = instantiate_node(SyntaxNode,input, index...(index + 1))
                @index += 1
              else
                terminal_parse_failure(':')
                r53 = nil
              end
              s41 << r53
              if r53
                r54 = _nt_h16
                s41 << r54
                if r54
                  if has_terminal?(':', false, index)
                    r55 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure(':')
                    r55 = nil
                  end
                  s41 << r55
                  if r55
                    r56 = _nt_h16
                    s41 << r56
                    if r56
                      if has_terminal?(':', false, index)
                        r57 = instantiate_node(SyntaxNode,input, index...(index + 1))
                        @index += 1
                      else
                        terminal_parse_failure(':')
                        r57 = nil
                      end
                      s41 << r57
                      if r57
                        r58 = _nt_ls32
                        s41 << r58
                      end
                    end
                  end
                end
              end
            end
          end
          if s41.last
            r41 = instantiate_node(SyntaxNode,input, i41...index, s41)
            r41.extend(IPv6address5)
          else
            @index = i41
            r41 = nil
          end
          if r41
            r0 = r41
          else
            i59, s59 = index, []
            i60 = index
            if has_terminal?('::', false, index)
              r61 = instantiate_node(SyntaxNode,input, index...(index + 2))
              @index += 2
            else
              terminal_parse_failure('::')
              r61 = nil
            end
            if r61
              r60 = r61
            else
              i62, s62 = index, []
              r63 = _nt_h16
              s62 << r63
              if r63
                if has_terminal?('::', false, index)
                  r64 = instantiate_node(SyntaxNode,input, index...(index + 2))
                  @index += 2
                else
                  terminal_parse_failure('::')
                  r64 = nil
                end
                s62 << r64
              end
              if s62.last
                r62 = instantiate_node(SyntaxNode,input, i62...index, s62)
                r62.extend(IPv6address6)
              else
                @index = i62
                r62 = nil
              end
              if r62
                r60 = r62
              else
                i65, s65 = index, []
                r66 = _nt_h16
                s65 << r66
                if r66
                  if has_terminal?(':', false, index)
                    r67 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure(':')
                    r67 = nil
                  end
                  s65 << r67
                  if r67
                    r68 = _nt_h16
                    s65 << r68
                    if r68
                      if has_terminal?('::', false, index)
                        r69 = instantiate_node(SyntaxNode,input, index...(index + 2))
                        @index += 2
                      else
                        terminal_parse_failure('::')
                        r69 = nil
                      end
                      s65 << r69
                    end
                  end
                end
                if s65.last
                  r65 = instantiate_node(SyntaxNode,input, i65...index, s65)
                  r65.extend(IPv6address7)
                else
                  @index = i65
                  r65 = nil
                end
                if r65
                  r60 = r65
                else
                  i70, s70 = index, []
                  r71 = _nt_h16
                  s70 << r71
                  if r71
                    if has_terminal?(':', false, index)
                      r72 = instantiate_node(SyntaxNode,input, index...(index + 1))
                      @index += 1
                    else
                      terminal_parse_failure(':')
                      r72 = nil
                    end
                    s70 << r72
                    if r72
                      r73 = _nt_h16
                      s70 << r73
                      if r73
                        if has_terminal?(':', false, index)
                          r74 = instantiate_node(SyntaxNode,input, index...(index + 1))
                          @index += 1
                        else
                          terminal_parse_failure(':')
                          r74 = nil
                        end
                        s70 << r74
                        if r74
                          r75 = _nt_h16
                          s70 << r75
                          if r75
                            if has_terminal?('::', false, index)
                              r76 = instantiate_node(SyntaxNode,input, index...(index + 2))
                              @index += 2
                            else
                              terminal_parse_failure('::')
                              r76 = nil
                            end
                            s70 << r76
                          end
                        end
                      end
                    end
                  end
                  if s70.last
                    r70 = instantiate_node(SyntaxNode,input, i70...index, s70)
                    r70.extend(IPv6address8)
                  else
                    @index = i70
                    r70 = nil
                  end
                  if r70
                    r60 = r70
                  else
                    @index = i60
                    r60 = nil
                  end
                end
              end
            end
            s59 << r60
            if r60
              r77 = _nt_h16
              s59 << r77
              if r77
                if has_terminal?(':', false, index)
                  r78 = instantiate_node(SyntaxNode,input, index...(index + 1))
                  @index += 1
                else
                  terminal_parse_failure(':')
                  r78 = nil
                end
                s59 << r78
                if r78
                  r79 = _nt_h16
                  s59 << r79
                  if r79
                    if has_terminal?(':', false, index)
                      r80 = instantiate_node(SyntaxNode,input, index...(index + 1))
                      @index += 1
                    else
                      terminal_parse_failure(':')
                      r80 = nil
                    end
                    s59 << r80
                    if r80
                      r81 = _nt_ls32
                      s59 << r81
                    end
                  end
                end
              end
            end
            if s59.last
              r59 = instantiate_node(SyntaxNode,input, i59...index, s59)
              r59.extend(IPv6address9)
            else
              @index = i59
              r59 = nil
            end
            if r59
              r0 = r59
            else
              i82, s82 = index, []
              i83 = index
              if has_terminal?('::', false, index)
                r84 = instantiate_node(SyntaxNode,input, index...(index + 2))
                @index += 2
              else
                terminal_parse_failure('::')
                r84 = nil
              end
              if r84
                r83 = r84
              else
                i85, s85 = index, []
                r86 = _nt_h16
                s85 << r86
                if r86
                  if has_terminal?('::', false, index)
                    r87 = instantiate_node(SyntaxNode,input, index...(index + 2))
                    @index += 2
                  else
                    terminal_parse_failure('::')
                    r87 = nil
                  end
                  s85 << r87
                end
                if s85.last
                  r85 = instantiate_node(SyntaxNode,input, i85...index, s85)
                  r85.extend(IPv6address10)
                else
                  @index = i85
                  r85 = nil
                end
                if r85
                  r83 = r85
                else
                  i88, s88 = index, []
                  r89 = _nt_h16
                  s88 << r89
                  if r89
                    if has_terminal?(':', false, index)
                      r90 = instantiate_node(SyntaxNode,input, index...(index + 1))
                      @index += 1
                    else
                      terminal_parse_failure(':')
                      r90 = nil
                    end
                    s88 << r90
                    if r90
                      r91 = _nt_h16
                      s88 << r91
                      if r91
                        if has_terminal?('::', false, index)
                          r92 = instantiate_node(SyntaxNode,input, index...(index + 2))
                          @index += 2
                        else
                          terminal_parse_failure('::')
                          r92 = nil
                        end
                        s88 << r92
                      end
                    end
                  end
                  if s88.last
                    r88 = instantiate_node(SyntaxNode,input, i88...index, s88)
                    r88.extend(IPv6address11)
                  else
                    @index = i88
                    r88 = nil
                  end
                  if r88
                    r83 = r88
                  else
                    i93, s93 = index, []
                    r94 = _nt_h16
                    s93 << r94
                    if r94
                      if has_terminal?(':', false, index)
                        r95 = instantiate_node(SyntaxNode,input, index...(index + 1))
                        @index += 1
                      else
                        terminal_parse_failure(':')
                        r95 = nil
                      end
                      s93 << r95
                      if r95
                        r96 = _nt_h16
                        s93 << r96
                        if r96
                          if has_terminal?(':', false, index)
                            r97 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r97 = nil
                          end
                          s93 << r97
                          if r97
                            r98 = _nt_h16
                            s93 << r98
                            if r98
                              if has_terminal?('::', false, index)
                                r99 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                @index += 2
                              else
                                terminal_parse_failure('::')
                                r99 = nil
                              end
                              s93 << r99
                            end
                          end
                        end
                      end
                    end
                    if s93.last
                      r93 = instantiate_node(SyntaxNode,input, i93...index, s93)
                      r93.extend(IPv6address12)
                    else
                      @index = i93
                      r93 = nil
                    end
                    if r93
                      r83 = r93
                    else
                      i100, s100 = index, []
                      r101 = _nt_h16
                      s100 << r101
                      if r101
                        if has_terminal?(':', false, index)
                          r102 = instantiate_node(SyntaxNode,input, index...(index + 1))
                          @index += 1
                        else
                          terminal_parse_failure(':')
                          r102 = nil
                        end
                        s100 << r102
                        if r102
                          r103 = _nt_h16
                          s100 << r103
                          if r103
                            if has_terminal?(':', false, index)
                              r104 = instantiate_node(SyntaxNode,input, index...(index + 1))
                              @index += 1
                            else
                              terminal_parse_failure(':')
                              r104 = nil
                            end
                            s100 << r104
                            if r104
                              r105 = _nt_h16
                              s100 << r105
                              if r105
                                if has_terminal?(':', false, index)
                                  r106 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                  @index += 1
                                else
                                  terminal_parse_failure(':')
                                  r106 = nil
                                end
                                s100 << r106
                                if r106
                                  r107 = _nt_h16
                                  s100 << r107
                                  if r107
                                    if has_terminal?('::', false, index)
                                      r108 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                      @index += 2
                                    else
                                      terminal_parse_failure('::')
                                      r108 = nil
                                    end
                                    s100 << r108
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                      if s100.last
                        r100 = instantiate_node(SyntaxNode,input, i100...index, s100)
                        r100.extend(IPv6address13)
                      else
                        @index = i100
                        r100 = nil
                      end
                      if r100
                        r83 = r100
                      else
                        @index = i83
                        r83 = nil
                      end
                    end
                  end
                end
              end
              s82 << r83
              if r83
                r109 = _nt_h16
                s82 << r109
                if r109
                  if has_terminal?(':', false, index)
                    r110 = instantiate_node(SyntaxNode,input, index...(index + 1))
                    @index += 1
                  else
                    terminal_parse_failure(':')
                    r110 = nil
                  end
                  s82 << r110
                  if r110
                    r111 = _nt_ls32
                    s82 << r111
                  end
                end
              end
              if s82.last
                r82 = instantiate_node(SyntaxNode,input, i82...index, s82)
                r82.extend(IPv6address14)
              else
                @index = i82
                r82 = nil
              end
              if r82
                r0 = r82
              else
                i112, s112 = index, []
                i113 = index
                if has_terminal?('::', false, index)
                  r114 = instantiate_node(SyntaxNode,input, index...(index + 2))
                  @index += 2
                else
                  terminal_parse_failure('::')
                  r114 = nil
                end
                if r114
                  r113 = r114
                else
                  i115, s115 = index, []
                  r116 = _nt_h16
                  s115 << r116
                  if r116
                    if has_terminal?('::', false, index)
                      r117 = instantiate_node(SyntaxNode,input, index...(index + 2))
                      @index += 2
                    else
                      terminal_parse_failure('::')
                      r117 = nil
                    end
                    s115 << r117
                  end
                  if s115.last
                    r115 = instantiate_node(SyntaxNode,input, i115...index, s115)
                    r115.extend(IPv6address15)
                  else
                    @index = i115
                    r115 = nil
                  end
                  if r115
                    r113 = r115
                  else
                    i118, s118 = index, []
                    r119 = _nt_h16
                    s118 << r119
                    if r119
                      if has_terminal?(':', false, index)
                        r120 = instantiate_node(SyntaxNode,input, index...(index + 1))
                        @index += 1
                      else
                        terminal_parse_failure(':')
                        r120 = nil
                      end
                      s118 << r120
                      if r120
                        r121 = _nt_h16
                        s118 << r121
                        if r121
                          if has_terminal?('::', false, index)
                            r122 = instantiate_node(SyntaxNode,input, index...(index + 2))
                            @index += 2
                          else
                            terminal_parse_failure('::')
                            r122 = nil
                          end
                          s118 << r122
                        end
                      end
                    end
                    if s118.last
                      r118 = instantiate_node(SyntaxNode,input, i118...index, s118)
                      r118.extend(IPv6address16)
                    else
                      @index = i118
                      r118 = nil
                    end
                    if r118
                      r113 = r118
                    else
                      i123, s123 = index, []
                      r124 = _nt_h16
                      s123 << r124
                      if r124
                        if has_terminal?(':', false, index)
                          r125 = instantiate_node(SyntaxNode,input, index...(index + 1))
                          @index += 1
                        else
                          terminal_parse_failure(':')
                          r125 = nil
                        end
                        s123 << r125
                        if r125
                          r126 = _nt_h16
                          s123 << r126
                          if r126
                            if has_terminal?(':', false, index)
                              r127 = instantiate_node(SyntaxNode,input, index...(index + 1))
                              @index += 1
                            else
                              terminal_parse_failure(':')
                              r127 = nil
                            end
                            s123 << r127
                            if r127
                              r128 = _nt_h16
                              s123 << r128
                              if r128
                                if has_terminal?('::', false, index)
                                  r129 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                  @index += 2
                                else
                                  terminal_parse_failure('::')
                                  r129 = nil
                                end
                                s123 << r129
                              end
                            end
                          end
                        end
                      end
                      if s123.last
                        r123 = instantiate_node(SyntaxNode,input, i123...index, s123)
                        r123.extend(IPv6address17)
                      else
                        @index = i123
                        r123 = nil
                      end
                      if r123
                        r113 = r123
                      else
                        i130, s130 = index, []
                        r131 = _nt_h16
                        s130 << r131
                        if r131
                          if has_terminal?(':', false, index)
                            r132 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r132 = nil
                          end
                          s130 << r132
                          if r132
                            r133 = _nt_h16
                            s130 << r133
                            if r133
                              if has_terminal?(':', false, index)
                                r134 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                @index += 1
                              else
                                terminal_parse_failure(':')
                                r134 = nil
                              end
                              s130 << r134
                              if r134
                                r135 = _nt_h16
                                s130 << r135
                                if r135
                                  if has_terminal?(':', false, index)
                                    r136 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                    @index += 1
                                  else
                                    terminal_parse_failure(':')
                                    r136 = nil
                                  end
                                  s130 << r136
                                  if r136
                                    r137 = _nt_h16
                                    s130 << r137
                                    if r137
                                      if has_terminal?('::', false, index)
                                        r138 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                        @index += 2
                                      else
                                        terminal_parse_failure('::')
                                        r138 = nil
                                      end
                                      s130 << r138
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                        if s130.last
                          r130 = instantiate_node(SyntaxNode,input, i130...index, s130)
                          r130.extend(IPv6address18)
                        else
                          @index = i130
                          r130 = nil
                        end
                        if r130
                          r113 = r130
                        else
                          i139, s139 = index, []
                          r140 = _nt_h16
                          s139 << r140
                          if r140
                            if has_terminal?(':', false, index)
                              r141 = instantiate_node(SyntaxNode,input, index...(index + 1))
                              @index += 1
                            else
                              terminal_parse_failure(':')
                              r141 = nil
                            end
                            s139 << r141
                            if r141
                              r142 = _nt_h16
                              s139 << r142
                              if r142
                                if has_terminal?(':', false, index)
                                  r143 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                  @index += 1
                                else
                                  terminal_parse_failure(':')
                                  r143 = nil
                                end
                                s139 << r143
                                if r143
                                  r144 = _nt_h16
                                  s139 << r144
                                  if r144
                                    if has_terminal?(':', false, index)
                                      r145 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                      @index += 1
                                    else
                                      terminal_parse_failure(':')
                                      r145 = nil
                                    end
                                    s139 << r145
                                    if r145
                                      r146 = _nt_h16
                                      s139 << r146
                                      if r146
                                        if has_terminal?(':', false, index)
                                          r147 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                          @index += 1
                                        else
                                          terminal_parse_failure(':')
                                          r147 = nil
                                        end
                                        s139 << r147
                                        if r147
                                          r148 = _nt_h16
                                          s139 << r148
                                          if r148
                                            if has_terminal?('::', false, index)
                                              r149 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                              @index += 2
                                            else
                                              terminal_parse_failure('::')
                                              r149 = nil
                                            end
                                            s139 << r149
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                          if s139.last
                            r139 = instantiate_node(SyntaxNode,input, i139...index, s139)
                            r139.extend(IPv6address19)
                          else
                            @index = i139
                            r139 = nil
                          end
                          if r139
                            r113 = r139
                          else
                            @index = i113
                            r113 = nil
                          end
                        end
                      end
                    end
                  end
                end
                s112 << r113
                if r113
                  r150 = _nt_ls32
                  s112 << r150
                end
                if s112.last
                  r112 = instantiate_node(SyntaxNode,input, i112...index, s112)
                  r112.extend(IPv6address20)
                else
                  @index = i112
                  r112 = nil
                end
                if r112
                  r0 = r112
                else
                  i151, s151 = index, []
                  i152 = index
                  if has_terminal?('::', false, index)
                    r153 = instantiate_node(SyntaxNode,input, index...(index + 2))
                    @index += 2
                  else
                    terminal_parse_failure('::')
                    r153 = nil
                  end
                  if r153
                    r152 = r153
                  else
                    i154, s154 = index, []
                    r155 = _nt_h16
                    s154 << r155
                    if r155
                      if has_terminal?('::', false, index)
                        r156 = instantiate_node(SyntaxNode,input, index...(index + 2))
                        @index += 2
                      else
                        terminal_parse_failure('::')
                        r156 = nil
                      end
                      s154 << r156
                    end
                    if s154.last
                      r154 = instantiate_node(SyntaxNode,input, i154...index, s154)
                      r154.extend(IPv6address21)
                    else
                      @index = i154
                      r154 = nil
                    end
                    if r154
                      r152 = r154
                    else
                      i157, s157 = index, []
                      r158 = _nt_h16
                      s157 << r158
                      if r158
                        if has_terminal?(':', false, index)
                          r159 = instantiate_node(SyntaxNode,input, index...(index + 1))
                          @index += 1
                        else
                          terminal_parse_failure(':')
                          r159 = nil
                        end
                        s157 << r159
                        if r159
                          r160 = _nt_h16
                          s157 << r160
                          if r160
                            if has_terminal?('::', false, index)
                              r161 = instantiate_node(SyntaxNode,input, index...(index + 2))
                              @index += 2
                            else
                              terminal_parse_failure('::')
                              r161 = nil
                            end
                            s157 << r161
                          end
                        end
                      end
                      if s157.last
                        r157 = instantiate_node(SyntaxNode,input, i157...index, s157)
                        r157.extend(IPv6address22)
                      else
                        @index = i157
                        r157 = nil
                      end
                      if r157
                        r152 = r157
                      else
                        i162, s162 = index, []
                        r163 = _nt_h16
                        s162 << r163
                        if r163
                          if has_terminal?(':', false, index)
                            r164 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r164 = nil
                          end
                          s162 << r164
                          if r164
                            r165 = _nt_h16
                            s162 << r165
                            if r165
                              if has_terminal?(':', false, index)
                                r166 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                @index += 1
                              else
                                terminal_parse_failure(':')
                                r166 = nil
                              end
                              s162 << r166
                              if r166
                                r167 = _nt_h16
                                s162 << r167
                                if r167
                                  if has_terminal?('::', false, index)
                                    r168 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                    @index += 2
                                  else
                                    terminal_parse_failure('::')
                                    r168 = nil
                                  end
                                  s162 << r168
                                end
                              end
                            end
                          end
                        end
                        if s162.last
                          r162 = instantiate_node(SyntaxNode,input, i162...index, s162)
                          r162.extend(IPv6address23)
                        else
                          @index = i162
                          r162 = nil
                        end
                        if r162
                          r152 = r162
                        else
                          i169, s169 = index, []
                          r170 = _nt_h16
                          s169 << r170
                          if r170
                            if has_terminal?(':', false, index)
                              r171 = instantiate_node(SyntaxNode,input, index...(index + 1))
                              @index += 1
                            else
                              terminal_parse_failure(':')
                              r171 = nil
                            end
                            s169 << r171
                            if r171
                              r172 = _nt_h16
                              s169 << r172
                              if r172
                                if has_terminal?(':', false, index)
                                  r173 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                  @index += 1
                                else
                                  terminal_parse_failure(':')
                                  r173 = nil
                                end
                                s169 << r173
                                if r173
                                  r174 = _nt_h16
                                  s169 << r174
                                  if r174
                                    if has_terminal?(':', false, index)
                                      r175 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                      @index += 1
                                    else
                                      terminal_parse_failure(':')
                                      r175 = nil
                                    end
                                    s169 << r175
                                    if r175
                                      r176 = _nt_h16
                                      s169 << r176
                                      if r176
                                        if has_terminal?('::', false, index)
                                          r177 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                          @index += 2
                                        else
                                          terminal_parse_failure('::')
                                          r177 = nil
                                        end
                                        s169 << r177
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                          if s169.last
                            r169 = instantiate_node(SyntaxNode,input, i169...index, s169)
                            r169.extend(IPv6address24)
                          else
                            @index = i169
                            r169 = nil
                          end
                          if r169
                            r152 = r169
                          else
                            i178, s178 = index, []
                            r179 = _nt_h16
                            s178 << r179
                            if r179
                              if has_terminal?(':', false, index)
                                r180 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                @index += 1
                              else
                                terminal_parse_failure(':')
                                r180 = nil
                              end
                              s178 << r180
                              if r180
                                r181 = _nt_h16
                                s178 << r181
                                if r181
                                  if has_terminal?(':', false, index)
                                    r182 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                    @index += 1
                                  else
                                    terminal_parse_failure(':')
                                    r182 = nil
                                  end
                                  s178 << r182
                                  if r182
                                    r183 = _nt_h16
                                    s178 << r183
                                    if r183
                                      if has_terminal?(':', false, index)
                                        r184 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                        @index += 1
                                      else
                                        terminal_parse_failure(':')
                                        r184 = nil
                                      end
                                      s178 << r184
                                      if r184
                                        r185 = _nt_h16
                                        s178 << r185
                                        if r185
                                          if has_terminal?(':', false, index)
                                            r186 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                            @index += 1
                                          else
                                            terminal_parse_failure(':')
                                            r186 = nil
                                          end
                                          s178 << r186
                                          if r186
                                            r187 = _nt_h16
                                            s178 << r187
                                            if r187
                                              if has_terminal?('::', false, index)
                                                r188 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                                @index += 2
                                              else
                                                terminal_parse_failure('::')
                                                r188 = nil
                                              end
                                              s178 << r188
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                            if s178.last
                              r178 = instantiate_node(SyntaxNode,input, i178...index, s178)
                              r178.extend(IPv6address25)
                            else
                              @index = i178
                              r178 = nil
                            end
                            if r178
                              r152 = r178
                            else
                              i189, s189 = index, []
                              r190 = _nt_h16
                              s189 << r190
                              if r190
                                if has_terminal?(':', false, index)
                                  r191 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                  @index += 1
                                else
                                  terminal_parse_failure(':')
                                  r191 = nil
                                end
                                s189 << r191
                                if r191
                                  r192 = _nt_h16
                                  s189 << r192
                                  if r192
                                    if has_terminal?(':', false, index)
                                      r193 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                      @index += 1
                                    else
                                      terminal_parse_failure(':')
                                      r193 = nil
                                    end
                                    s189 << r193
                                    if r193
                                      r194 = _nt_h16
                                      s189 << r194
                                      if r194
                                        if has_terminal?(':', false, index)
                                          r195 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                          @index += 1
                                        else
                                          terminal_parse_failure(':')
                                          r195 = nil
                                        end
                                        s189 << r195
                                        if r195
                                          r196 = _nt_h16
                                          s189 << r196
                                          if r196
                                            if has_terminal?(':', false, index)
                                              r197 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                              @index += 1
                                            else
                                              terminal_parse_failure(':')
                                              r197 = nil
                                            end
                                            s189 << r197
                                            if r197
                                              r198 = _nt_h16
                                              s189 << r198
                                              if r198
                                                if has_terminal?(':', false, index)
                                                  r199 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                                  @index += 1
                                                else
                                                  terminal_parse_failure(':')
                                                  r199 = nil
                                                end
                                                s189 << r199
                                                if r199
                                                  r200 = _nt_h16
                                                  s189 << r200
                                                  if r200
                                                    if has_terminal?('::', false, index)
                                                      r201 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                                      @index += 2
                                                    else
                                                      terminal_parse_failure('::')
                                                      r201 = nil
                                                    end
                                                    s189 << r201
                                                  end
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                              if s189.last
                                r189 = instantiate_node(SyntaxNode,input, i189...index, s189)
                                r189.extend(IPv6address26)
                              else
                                @index = i189
                                r189 = nil
                              end
                              if r189
                                r152 = r189
                              else
                                @index = i152
                                r152 = nil
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                  s151 << r152
                  if r152
                    r202 = _nt_h16
                    s151 << r202
                  end
                  if s151.last
                    r151 = instantiate_node(SyntaxNode,input, i151...index, s151)
                    r151.extend(IPv6address27)
                  else
                    @index = i151
                    r151 = nil
                  end
                  if r151
                    r0 = r151
                  else
                    i203 = index
                    if has_terminal?('::', false, index)
                      r204 = instantiate_node(SyntaxNode,input, index...(index + 2))
                      @index += 2
                    else
                      terminal_parse_failure('::')
                      r204 = nil
                    end
                    if r204
                      r203 = r204
                    else
                      i205, s205 = index, []
                      r206 = _nt_h16
                      s205 << r206
                      if r206
                        if has_terminal?('::', false, index)
                          r207 = instantiate_node(SyntaxNode,input, index...(index + 2))
                          @index += 2
                        else
                          terminal_parse_failure('::')
                          r207 = nil
                        end
                        s205 << r207
                      end
                      if s205.last
                        r205 = instantiate_node(SyntaxNode,input, i205...index, s205)
                        r205.extend(IPv6address28)
                      else
                        @index = i205
                        r205 = nil
                      end
                      if r205
                        r203 = r205
                      else
                        i208, s208 = index, []
                        r209 = _nt_h16
                        s208 << r209
                        if r209
                          if has_terminal?(':', false, index)
                            r210 = instantiate_node(SyntaxNode,input, index...(index + 1))
                            @index += 1
                          else
                            terminal_parse_failure(':')
                            r210 = nil
                          end
                          s208 << r210
                          if r210
                            r211 = _nt_h16
                            s208 << r211
                            if r211
                              if has_terminal?('::', false, index)
                                r212 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                @index += 2
                              else
                                terminal_parse_failure('::')
                                r212 = nil
                              end
                              s208 << r212
                            end
                          end
                        end
                        if s208.last
                          r208 = instantiate_node(SyntaxNode,input, i208...index, s208)
                          r208.extend(IPv6address29)
                        else
                          @index = i208
                          r208 = nil
                        end
                        if r208
                          r203 = r208
                        else
                          i213, s213 = index, []
                          r214 = _nt_h16
                          s213 << r214
                          if r214
                            if has_terminal?(':', false, index)
                              r215 = instantiate_node(SyntaxNode,input, index...(index + 1))
                              @index += 1
                            else
                              terminal_parse_failure(':')
                              r215 = nil
                            end
                            s213 << r215
                            if r215
                              r216 = _nt_h16
                              s213 << r216
                              if r216
                                if has_terminal?(':', false, index)
                                  r217 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                  @index += 1
                                else
                                  terminal_parse_failure(':')
                                  r217 = nil
                                end
                                s213 << r217
                                if r217
                                  r218 = _nt_h16
                                  s213 << r218
                                  if r218
                                    if has_terminal?('::', false, index)
                                      r219 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                      @index += 2
                                    else
                                      terminal_parse_failure('::')
                                      r219 = nil
                                    end
                                    s213 << r219
                                  end
                                end
                              end
                            end
                          end
                          if s213.last
                            r213 = instantiate_node(SyntaxNode,input, i213...index, s213)
                            r213.extend(IPv6address30)
                          else
                            @index = i213
                            r213 = nil
                          end
                          if r213
                            r203 = r213
                          else
                            i220, s220 = index, []
                            r221 = _nt_h16
                            s220 << r221
                            if r221
                              if has_terminal?(':', false, index)
                                r222 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                @index += 1
                              else
                                terminal_parse_failure(':')
                                r222 = nil
                              end
                              s220 << r222
                              if r222
                                r223 = _nt_h16
                                s220 << r223
                                if r223
                                  if has_terminal?(':', false, index)
                                    r224 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                    @index += 1
                                  else
                                    terminal_parse_failure(':')
                                    r224 = nil
                                  end
                                  s220 << r224
                                  if r224
                                    r225 = _nt_h16
                                    s220 << r225
                                    if r225
                                      if has_terminal?(':', false, index)
                                        r226 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                        @index += 1
                                      else
                                        terminal_parse_failure(':')
                                        r226 = nil
                                      end
                                      s220 << r226
                                      if r226
                                        r227 = _nt_h16
                                        s220 << r227
                                        if r227
                                          if has_terminal?('::', false, index)
                                            r228 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                            @index += 2
                                          else
                                            terminal_parse_failure('::')
                                            r228 = nil
                                          end
                                          s220 << r228
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                            if s220.last
                              r220 = instantiate_node(SyntaxNode,input, i220...index, s220)
                              r220.extend(IPv6address31)
                            else
                              @index = i220
                              r220 = nil
                            end
                            if r220
                              r203 = r220
                            else
                              i229, s229 = index, []
                              r230 = _nt_h16
                              s229 << r230
                              if r230
                                if has_terminal?(':', false, index)
                                  r231 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                  @index += 1
                                else
                                  terminal_parse_failure(':')
                                  r231 = nil
                                end
                                s229 << r231
                                if r231
                                  r232 = _nt_h16
                                  s229 << r232
                                  if r232
                                    if has_terminal?(':', false, index)
                                      r233 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                      @index += 1
                                    else
                                      terminal_parse_failure(':')
                                      r233 = nil
                                    end
                                    s229 << r233
                                    if r233
                                      r234 = _nt_h16
                                      s229 << r234
                                      if r234
                                        if has_terminal?(':', false, index)
                                          r235 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                          @index += 1
                                        else
                                          terminal_parse_failure(':')
                                          r235 = nil
                                        end
                                        s229 << r235
                                        if r235
                                          r236 = _nt_h16
                                          s229 << r236
                                          if r236
                                            if has_terminal?(':', false, index)
                                              r237 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                              @index += 1
                                            else
                                              terminal_parse_failure(':')
                                              r237 = nil
                                            end
                                            s229 << r237
                                            if r237
                                              r238 = _nt_h16
                                              s229 << r238
                                              if r238
                                                if has_terminal?('::', false, index)
                                                  r239 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                                  @index += 2
                                                else
                                                  terminal_parse_failure('::')
                                                  r239 = nil
                                                end
                                                s229 << r239
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                              if s229.last
                                r229 = instantiate_node(SyntaxNode,input, i229...index, s229)
                                r229.extend(IPv6address32)
                              else
                                @index = i229
                                r229 = nil
                              end
                              if r229
                                r203 = r229
                              else
                                i240, s240 = index, []
                                r241 = _nt_h16
                                s240 << r241
                                if r241
                                  if has_terminal?(':', false, index)
                                    r242 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                    @index += 1
                                  else
                                    terminal_parse_failure(':')
                                    r242 = nil
                                  end
                                  s240 << r242
                                  if r242
                                    r243 = _nt_h16
                                    s240 << r243
                                    if r243
                                      if has_terminal?(':', false, index)
                                        r244 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                        @index += 1
                                      else
                                        terminal_parse_failure(':')
                                        r244 = nil
                                      end
                                      s240 << r244
                                      if r244
                                        r245 = _nt_h16
                                        s240 << r245
                                        if r245
                                          if has_terminal?(':', false, index)
                                            r246 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                            @index += 1
                                          else
                                            terminal_parse_failure(':')
                                            r246 = nil
                                          end
                                          s240 << r246
                                          if r246
                                            r247 = _nt_h16
                                            s240 << r247
                                            if r247
                                              if has_terminal?(':', false, index)
                                                r248 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                                @index += 1
                                              else
                                                terminal_parse_failure(':')
                                                r248 = nil
                                              end
                                              s240 << r248
                                              if r248
                                                r249 = _nt_h16
                                                s240 << r249
                                                if r249
                                                  if has_terminal?(':', false, index)
                                                    r250 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                                    @index += 1
                                                  else
                                                    terminal_parse_failure(':')
                                                    r250 = nil
                                                  end
                                                  s240 << r250
                                                  if r250
                                                    r251 = _nt_h16
                                                    s240 << r251
                                                    if r251
                                                      if has_terminal?('::', false, index)
                                                        r252 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                                        @index += 2
                                                      else
                                                        terminal_parse_failure('::')
                                                        r252 = nil
                                                      end
                                                      s240 << r252
                                                    end
                                                  end
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                                if s240.last
                                  r240 = instantiate_node(SyntaxNode,input, i240...index, s240)
                                  r240.extend(IPv6address33)
                                else
                                  @index = i240
                                  r240 = nil
                                end
                                if r240
                                  r203 = r240
                                else
                                  i253, s253 = index, []
                                  r254 = _nt_h16
                                  s253 << r254
                                  if r254
                                    if has_terminal?(':', false, index)
                                      r255 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                      @index += 1
                                    else
                                      terminal_parse_failure(':')
                                      r255 = nil
                                    end
                                    s253 << r255
                                    if r255
                                      r256 = _nt_h16
                                      s253 << r256
                                      if r256
                                        if has_terminal?(':', false, index)
                                          r257 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                          @index += 1
                                        else
                                          terminal_parse_failure(':')
                                          r257 = nil
                                        end
                                        s253 << r257
                                        if r257
                                          r258 = _nt_h16
                                          s253 << r258
                                          if r258
                                            if has_terminal?(':', false, index)
                                              r259 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                              @index += 1
                                            else
                                              terminal_parse_failure(':')
                                              r259 = nil
                                            end
                                            s253 << r259
                                            if r259
                                              r260 = _nt_h16
                                              s253 << r260
                                              if r260
                                                if has_terminal?(':', false, index)
                                                  r261 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                                  @index += 1
                                                else
                                                  terminal_parse_failure(':')
                                                  r261 = nil
                                                end
                                                s253 << r261
                                                if r261
                                                  r262 = _nt_h16
                                                  s253 << r262
                                                  if r262
                                                    if has_terminal?(':', false, index)
                                                      r263 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                                      @index += 1
                                                    else
                                                      terminal_parse_failure(':')
                                                      r263 = nil
                                                    end
                                                    s253 << r263
                                                    if r263
                                                      r264 = _nt_h16
                                                      s253 << r264
                                                      if r264
                                                        if has_terminal?(':', false, index)
                                                          r265 = instantiate_node(SyntaxNode,input, index...(index + 1))
                                                          @index += 1
                                                        else
                                                          terminal_parse_failure(':')
                                                          r265 = nil
                                                        end
                                                        s253 << r265
                                                        if r265
                                                          r266 = _nt_h16
                                                          s253 << r266
                                                          if r266
                                                            if has_terminal?('::', false, index)
                                                              r267 = instantiate_node(SyntaxNode,input, index...(index + 2))
                                                              @index += 2
                                                            else
                                                              terminal_parse_failure('::')
                                                              r267 = nil
                                                            end
                                                            s253 << r267
                                                          end
                                                        end
                                                      end
                                                    end
                                                  end
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                  if s253.last
                                    r253 = instantiate_node(SyntaxNode,input, i253...index, s253)
                                    r253.extend(IPv6address34)
                                  else
                                    @index = i253
                                    r253 = nil
                                  end
                                  if r253
                                    r203 = r253
                                  else
                                    @index = i203
                                    r203 = nil
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                    if r203
                      r0 = r203
                    else
                      @index = i0
                      r0 = nil
                    end
                  end
                end
              end
            end
          end
        end
      end
    end

    node_cache[:IPv6address][start_index] = r0

    r0
  end

  module H160
    def HEXDIG
      elements[0]
    end

  end

  def _nt_h16
    start_index = index
    if node_cache[:h16].has_key?(index)
      cached = node_cache[:h16][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0, s0 = index, []
    r1 = _nt_HEXDIG
    s0 << r1
    if r1
      r3 = _nt_HEXDIG
      if r3
        r2 = r3
      else
        r2 = instantiate_node(SyntaxNode,input, index...index)
      end
      s0 << r2
      if r2
        r5 = _nt_HEXDIG
        if r5
          r4 = r5
        else
          r4 = instantiate_node(SyntaxNode,input, index...index)
        end
        s0 << r4
        if r4
          r7 = _nt_HEXDIG
          if r7
            r6 = r7
          else
            r6 = instantiate_node(SyntaxNode,input, index...index)
          end
          s0 << r6
        end
      end
    end
    if s0.last
      r0 = instantiate_node(SyntaxNode,input, i0...index, s0)
      r0.extend(H160)
    else
      @index = i0
      r0 = nil
    end

    node_cache[:h16][start_index] = r0

    r0
  end

  module Ls320
    def h161
      elements[0]
    end

    def h162
      elements[2]
    end
  end

  def _nt_ls32
    start_index = index
    if node_cache[:ls32].has_key?(index)
      cached = node_cache[:ls32][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    i0 = index
    i1, s1 = index, []
    r2 = _nt_h16
    s1 << r2
    if r2
      if has_terminal?(":", false, index)
        r3 = instantiate_node(SyntaxNode,input, index...(index + 1))
        @index += 1
      else
        terminal_parse_failure(":")
        r3 = nil
      end
      s1 << r3
      if r3
        r4 = _nt_h16
        s1 << r4
      end
    end
    if s1.last
      r1 = instantiate_node(SyntaxNode,input, i1...index, s1)
      r1.extend(Ls320)
    else
      @index = i1
      r1 = nil
    end
    if r1
      r0 = r1
    else
      r5 = _nt_IPv4address
      if r5
        r0 = r5
      else
        @index = i0
        r0 = nil
      end
    end

    node_cache[:ls32][start_index] = r0

    r0
  end

  def _nt_DIGIT
    start_index = index
    if node_cache[:DIGIT].has_key?(index)
      cached = node_cache[:DIGIT][index]
      if cached
        cached = SyntaxNode.new(input, index...(index + 1)) if cached == true
        @index = cached.interval.end
      end
      return cached
    end

    if has_terminal?('\G[\\x30-\\x39]', true, index)
      r0 = instantiate_node(SyntaxNode,input, index...(index + 1))
      @index += 1
    else
      r0 = nil
    end

    node_cache[:DIGIT][start_index] = r0

    r0
  end

end

class IPParser < Treetop::Runtime::CompiledParser
  include IP
end

